### PR TITLE
Migrate to RxJava 3

### LINKED ISSUE #690: RxJava 3.x support
The [RxJava docs](https://github.com/ReactiveX/RxJava) mention the following:

> The 2.x version is in maintenance mode and will be supported only through bugfixes until February 28, 2021. No new features, behavior changes or documentation adjustments will be accepted or applied to 2.x.

Are there any plans for e.g. rxandroidble3?

Or will the rxandroidble2 be compatible with the RxJava 3.x version?

### PR DESCRIPTION
**Pull request by z3ntu**
Based on `test/rxjava3` branch with updated imports & dependency updates for rxjava3.

As far as I can tell, all the tests are succeeding.

What's missing:

* ~~Some test files still contain "old imports" as function names, e.g. `NotificationAndIndicationManagerTest.groovy`~~
* ~~Some doc strings still have the old imports, e.g. `BleAlreadyConnectedException.java`~~

Fixes #690

### CODE REVIEW

**Comment by dariuszseweryn** [comment]
Thanks for helping with the work. Unfortunately I cannot accept this PR until you will sign the CLA.

If you would have time to fix imports, docs and change package name to `rxandroidble3` it would be awesome.

**Comment by z3ntu** [comment]
@dariuszseweryn I'm struggling at the moment to build the library to my local maven repository. Generally `gradle rxandroidble:install mockrxandroidble:install dagger-library-shadow:install` seems to work but the resulting pom at `~/.m2/repository/com/polidea/rxandroidble2/rxandroidble/1.11.1-SNAPSHOT/rxandroidble-1.11.1-SNAPSHOT.pom` is missing all dependency information for some reason which I haven't figured out why. Any idea?

**Comment by z3ntu** [comment]
@dariuszseweryn ping?

**Comment by vanwesm** [comment]
Any news here ? because RxJava2 will soon be not supported anymore : https://bioserenity.atlassian.net/browse/MA-3566

**Comment by z3ntu** [comment]
I've noticed when using the lib built on jitpack.io (and manually adding back the dependencies, see my comments above) this:

>    Somehow some desugaring component doesn't translate one static interface
>    call correctly which makes the app crash at runtime.
>    
>    Reproducible with deleting the app apk, ./gradlew assemblePreview
>    and install that apk.
>    
>    When decompiling it (e.g. with apktool) use this command to view if the
>    error exists:
>    grep -r "fromAction(Lio/reactivex/rxjava3/functions/Action;)Lio/reactivex/rxjava3/disposables/Disposable"

**Comment by z3ntu** [comment]
The previous comment seems to be caused by https://issuetracker.google.com/issues/183632445 , workaround there is to put `android.enableDexingArtifactTransform=false` into your `gradle.properties`

**Comment by z3ntu** [comment]
FYI I'll probably only be able to work on this until the end of May, after that somebody else will have to complete the PR.

**Comment by Drjacky** [comment]
@z3ntu @dariuszseweryn Any update on this PR? 🙏🏼

**Comment by Drjacky** [comment]
@z3ntu I wanted to continue your PR but, I get this:
```groovy
ERROR: Permission to z3ntu/RxAndroidBle.git denied to Drjacky.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

seems you need to check something  like
> Allow edits from maintainers.

**Comment by z3ntu** [comment]
@Drjacky You're not maintainer which is why you don't have permission to push. The checkbox was on. I've given you direct access now though. 

Feel free to rebase and fix up the rest etc. I've kept the last couple of commits un-squashed on purpose to allow to reproduce them in case upstream changes (which it did again as you can see). When it's getting close to be merged (maybe this will happen at some point..?) then just squash them together but please keep me as author. Good luck :)

**Comment by Drjacky** [comment]
@dariuszseweryn Please check Readme file to see if you're happy with `### Gradle` and `### Maven` sections as they're still pointing to `.rxandroidble2`.

Also, in `gradle.properties`:
```
GROUP=com.polidea.rxandroidble3
VERSION_NAME=1.12.2
```

Let me know if you want me to change them to something.

**Comment by Drjacky** [comment]
@dariuszseweryn @z3ntu Anything else we need to do to have this PR to be merged?

**Comment by Drjacky** [comment]
I've resolved the conflicts.
@z3ntu @dariuszseweryn Please check the PR if applicable. 🙏🏼

**Comment by MarekMacko** [comment]
@dariuszseweryn Is there any plan to update this amazing library with RxJava 3 😃 ? I'm really looking forward to it 🔥

**Comment by nateridderman** [comment]
https://twitter.com/DSeweryn/status/1369016230095511554

**Comment by dariuszseweryn** [comment]
I have still this in plans. I am currently working on merging #770 which should unlock me a bit but I must keep the ability to release the library

**Comment by teddyvn** [comment]
Waiting for this PR merging. Thanks

**Comment by dariuszseweryn** [comment]
RxJava 3 based dependency is now on Maven Central under `com.polidea.rxandroidble3:rxandroidble:1.15.0`. I am sorry for such a long wait and would like to thank you all for the support. RxJava 2 based dependency is still supported for the time being under the usual `com.polidea.rxandroidble2:rxandroidble:1.15.0`. Cheers!

**Pull request closed without merging**
