### PR TITLE
Add isConnectable to ScanResult

### PR DESCRIPTION
**Pull request by MartinSadovy**
Hi I finished implementation by https://github.com/dariuszseweryn/RxAndroidBle/pull/689 and tested on many devices .

Code review MR suggested: IsConnectableStatus ✅ 
After discussion on original MR, author added `isLegacy`, which is INCORRECT. So I removed it. isLegacy can be true for peripheral devices but it is independent on isConnectable. 

We tested the behaviour on many devices (A7 to A12) and it works correctly.

### CODE REVIEW

**Comment by nrbrook** [comment]
I decided to fork this project so we can maintain it more actively and merge PRs. I've forked at https://github.com/NRB-Tech/RxAndroidBle/ and it's on Maven Central as io.nrbtech.rxandroidble. If you want to submit this PR there I will review.

**Comment by nrbrook** [comment]
I have effectively merged this PR and released as `io.nrbtech.rxandroidble:rxandroidble:2.0.0` on maven central.

**Review by dariuszseweryn — APPROVED** [review]
Awesome! I added few things to my liking. Sorry for waiting so long — I took quite some time off and misconfigured my notifications so I was blind for events here. Thank you very much for your contribution 🚀

**Comment by MartinSadovy** [comment]
Thanks! When are you planning to release new version? :)

**Comment by dariuszseweryn** [comment]
You can preview on `1.14.0-SNAPSHOT` and report if that works for you

**Pull request merged**
